---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-blade1
  labels:
    cluster-name: edge-demo
spec:
  config:
    dns-resolver:
      config:
        server:
          - 10.6.1.3
    interfaces:
      - ipv4:
          address:
            - ip: 10.16.16.12
              prefix-length: 24
          enabled: true
        name: ens43f0
        state: up
        type: ethernet
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.16.16.1
          next-hop-interface: ens43f0
  interfaces:
    - name: ens43f0
      macAddress: B4:96:91:BF:CC:20