---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sno
namePrefix: gitops-
nameSuffix: -oe

bases:
  - github.com/telenor-labs/gitops-ocp-base/base/sno?ref=main

patchesStrategicMerge:
  - ./patches/nmstate-config.yaml
  - ./patches/aci.yaml

patches:
  - target:
      version: v1
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/labels/name
        value: 'gitops-sno-oe'
  - target:
      kind: AgentClusterInstall
    patch: |-
      - op: replace
        path: /spec/clusterDeploymentRef/name
        value: 'gitops-sno-oe'
      - op: replace
        path: /metadata/name
        value: 'gitops-sno-oe'
  - target:
      kind: SealedSecret
    patch: |-
      - op: replace
        path: /spec/template/metadata/namespace
        value: 'gitops-sno-oe'
  - target:
      kind: Secret
      name: bmc-sno
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'gitops-sno-oe-bmc-sno'
  - target:
      kind: ManagedCluster
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'gitops-sno-oe'
  - target:
      kind: BareMetalHost
      name: sno
    path: ./patches/bmh-gitops-sno-oe-sno-patch.yaml
  - target:
      kind: ClusterDeployment
    path: ./patches/clusterdeployment-patch.yaml
  - target:
      kind: InfraEnv
    path: ./patches/infraenv-patch.yaml
  - target:
      kind: KlusterletAddonConfig
    path: ./patches/klusterletaddon-patch.yaml
