---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-sno-oe

resources:
  - ../default/

patches:
  - target:
      version: v1
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/labels/name
        value: 'gitops-sno-oe'
  - target:
      kind: Secret
      name: bmc-day2-worker1
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'bmc-du1-fec1-gitops-sno-oe'
  - target:
      kind: BareMetalHost
      name: bmh-day2-worker1
    path: ./patches/bmh-du1-fec1-gitops-sno-oe.yaml
  - target:
      kind: NMStateConfig
      name: nmstate-day2-worker1
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'nmstate-du1-fec1-gitops-sno-oe'
  - target:
      kind: NMStateConfig
    patch: |-
      - op: replace
        path: /metadata/labels/cluster-name
        value: 'gitops-sno-oe'
